export type Action =
// accesso
  | "DASHBOARD.VIEW"
  | "FASCICOLO.VIEW_ALL"
  | "FASCICOLO.VIEW_OWN"

  // presa in carico iniziale (venditore)
  | "FASCICOLO.TAKE_COMM"

  // commerciale
  | "FASCICOLO.EDIT_OWN"
  | "FASCICOLO.SEND_AS_COMM"
  | "FASCICOLO.REQUEST_REOPEN"

  // backoffice (aree)
  | "FASCICOLO.TAKE_BO"
  | "FASCICOLO.TAKE_BOF"
  | "FASCICOLO.TAKE_BOU"
  | "FASCICOLO.VALIDATE_BO"
  | "FASCICOLO.VALIDATE_BOF"
  | "FASCICOLO.VALIDATE_BOU"
  | "FASCICOLO.REQUEST_REVIEW_BO"
  | "FASCICOLO.REQUEST_REVIEW_BOF"
  | "FASCICOLO.REQUEST_REVIEW_BOU"
  | "FASCICOLO.REOPEN"

  // consegna
  | "DELIVERY.TAKE"
  | "DELIVERY.UPLOAD"
  | "DELIVERY.SEND_TO_VRC"
  | "VRC.TAKE"
  | "VRC.VALIDATE"
  | "VRC.REQUEST_FIX"

  // amministrativo/responsabile/admin
  | "FATTURA.UPLOAD"
  | "BACKOFFICE.REASSIGN"
  | "ADMIN.DOC_RULES_MANAGE";
